// <auto-generated />
using System;
using DigitalDetectiveAgency.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalDetectiveAgency.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260804025521_DropInitialFourCases")]
    partial class DropInitialFourCases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Accusation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccusedSuspectId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccusedSuspectId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CaseId");

                    b.ToTable("Accusations");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCompletedTutorial")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A world-renowned violinist disappears moments before a sold-out concert. No signs of forced entry. No witnesses. Just an empty dressing room and a single dropped rose.",
                            Difficulty = 0,
                            IsPublished = true,
                            Title = "The Vanishing Violinist"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Community radio host Miguel Ramos is found dead moments after his live broadcast suddenly cuts off. Everyone blames the rolling blackout. But one small detail proves the station never actually lost power.",
                            Difficulty = 1,
                            IsPublished = true,
                            Title = "The Last Broadcast"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The night of the town fiesta, sugar baron Ernesto Malinao is found dead in his study at the family's ancestral hacienda in Negros Occidental hours before he was set to sign the papers selling generations of tenant land to a foreign conglomerate. The house was full of relatives, guests, and household staff. Everyone was watching the fireworks. No one saw a thing.",
                            Difficulty = 2,
                            IsPublished = true,
                            Title = "The Last Harvest at Hacienda Malinao"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The night before dive resort owner Ramon Aguilar was set to unveil a controversial expansion into Talipanan Cove land the local fisherfolk have worked for generations and the Mangyan community considers ancestral ground he's found dead at the bottom of his own boat dock. The town had gathered for the resort's investor showcase. Protesters had gathered outside the gate for weeks. Everyone had a reason to want the expansion stopped. Only one person had a reason to stop Ramon himself.",
                            Difficulty = 2,
                            IsPublished = true,
                            Title = "Undertow at Puerto Galera"
                        });
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.CaseConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int>("FromId")
                        .HasColumnType("int");

                    b.Property<string>("FromType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToId")
                        .HasColumnType("int");

                    b.Property<string>("ToType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("CaseConnections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseId = 1,
                            FromId = 2,
                            FromType = "Evidence",
                            ToId = 2,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 2,
                            CaseId = 1,
                            FromId = 2,
                            FromType = "Witness",
                            ToId = 2,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 3,
                            CaseId = 1,
                            FromId = 7,
                            FromType = "Evidence",
                            ToId = 2,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 4,
                            CaseId = 2,
                            FromId = 26,
                            FromType = "Evidence",
                            ToId = 25,
                            ToType = "Evidence"
                        },
                        new
                        {
                            Id = 5,
                            CaseId = 2,
                            FromId = 24,
                            FromType = "Evidence",
                            ToId = 25,
                            ToType = "Evidence"
                        },
                        new
                        {
                            Id = 6,
                            CaseId = 2,
                            FromId = 27,
                            FromType = "Evidence",
                            ToId = 22,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 7,
                            CaseId = 2,
                            FromId = 28,
                            FromType = "Evidence",
                            ToId = 22,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 8,
                            CaseId = 2,
                            FromId = 29,
                            FromType = "Evidence",
                            ToId = 22,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 9,
                            CaseId = 3,
                            FromId = 9,
                            FromType = "Evidence",
                            ToId = 10,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 10,
                            CaseId = 3,
                            FromId = 10,
                            FromType = "Evidence",
                            ToId = 10,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 11,
                            CaseId = 3,
                            FromId = 8,
                            FromType = "Witness",
                            ToId = 10,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 12,
                            CaseId = 4,
                            FromId = 17,
                            FromType = "Evidence",
                            ToId = 12,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 13,
                            CaseId = 4,
                            FromId = 18,
                            FromType = "Evidence",
                            ToId = 12,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 14,
                            CaseId = 4,
                            FromId = 13,
                            FromType = "Witness",
                            ToId = 12,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 15,
                            CaseId = 4,
                            FromId = 17,
                            FromType = "Evidence",
                            ToId = 18,
                            ToType = "Evidence"
                        },
                        new
                        {
                            Id = 16,
                            CaseId = 4,
                            FromId = 18,
                            FromType = "Evidence",
                            ToId = 13,
                            ToType = "Witness"
                        });
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.ClueConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromId")
                        .HasColumnType("int");

                    b.Property<string>("FromType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToId")
                        .HasColumnType("int");

                    b.Property<string>("ToType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CaseId");

                    b.ToTable("ClueConnections");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.ConnectionAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromId")
                        .HasColumnType("int");

                    b.Property<string>("FromType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToId")
                        .HasColumnType("int");

                    b.Property<string>("ToType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WasCorrect")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CaseId");

                    b.ToTable("ConnectionAttempts");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("EvidenceItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseId = 1,
                            Description = "A single red rose found on the dressing room floor. The stem is freshly cut, not wilted someone left it here recently.",
                            ImageUrl = "/images/evidence/rose.jpg",
                            Name = "Dropped Rose"
                        },
                        new
                        {
                            Id = 2,
                            CaseId = 1,
                            Description = "A concert program torn roughly in half. The violinist's name has been circled in red ink, and a small phone number is scrawled in the margin.",
                            ImageUrl = "/images/evidence/torn_program.jpg",
                            Name = "Torn Concert Program"
                        },
                        new
                        {
                            Id = 4,
                            CaseId = 1,
                            Description = "A photocopied ledger page with several transactions circled and the word 'AUDIT' underlined twice. Found stuffed in a lobby trash can.",
                            ImageUrl = "/images/evidence/ledger.jpg",
                            Name = "Insurance Ledger Page"
                        },
                        new
                        {
                            Id = 5,
                            CaseId = 1,
                            Description = "A crumpled note reading: 'We need to talk. I'm not done fighting for us.' No signature, but the handwriting is bold and impatient.",
                            ImageUrl = "/images/evidence/note.jpg",
                            Name = "Handwritten Note"
                        },
                        new
                        {
                            Id = 6,
                            CaseId = 1,
                            Description = "A printed transcript of a voicemail: 'You can't just cut me out after everything I've done for you. We'll see about that.' Timestamp: three days before the disappearance.",
                            ImageUrl = "/images/evidence/voicemail.jpg",
                            Name = "Voicemail Transcript"
                        },
                        new
                        {
                            Id = 7,
                            CaseId = 1,
                            Description = "A printout of badge-scan entries. One badge registered to Elena Vasquez scanned into the dressing room corridor at 7:38 PM, twenty minutes before the violinist was last seen.",
                            ImageUrl = "/images/evidence/security_log.jpg",
                            Name = "Backstage Security Log"
                        },
                        new
                        {
                            Id = 24,
                            CaseId = 2,
                            Description = "Miguel died from a single blunt force trauma to the back of the head. Estimated time of death: 9:17 PM.",
                            ImageUrl = "/images/evidence/autopsy_report.jpg",
                            Name = "Autopsy Report"
                        },
                        new
                        {
                            Id = 25,
                            CaseId = 2,
                            Description = "The live broadcast ends abruptly at exactly 9:17 PM. No scream, no struggle-only sudden silence.",
                            ImageUrl = "/images/evidence/broadcast_recording.jpg",
                            Name = "Broadcast Recording"
                        },
                        new
                        {
                            Id = 26,
                            CaseId = 2,
                            Description = "The backup generator automatically activated at 9:16 PM and supplied uninterrupted power until 9:19 PM.",
                            ImageUrl = "/images/evidence/generator_log.jpg",
                            Name = "Generator Log"
                        },
                        new
                        {
                            Id = 27,
                            CaseId = 2,
                            Description = "A flashlight recovered from Marco's toolbox. Rainwater is mixed with fiberglass insulation dust matching the generator shed.",
                            ImageUrl = "/images/evidence/wet_flashlight.jpg",
                            Name = "Wet Flashlight"
                        },
                        new
                        {
                            Id = 28,
                            CaseId = 2,
                            Description = "Several maintenance expenses were redirected into an unknown personal account over the past six months.",
                            ImageUrl = "/images/evidence/budget_spreadsheet.jpg",
                            Name = "Maintenance Budget Spreadsheet"
                        },
                        new
                        {
                            Id = 29,
                            CaseId = 2,
                            Description = "Miguel recorded a message saying, 'Marco... we'll figure this out tomorrow. Your son shouldn't suffer because of this.' The recording was never sent.",
                            ImageUrl = "/images/evidence/voice_memo.jpg",
                            Name = "Unsent Voice Memo"
                        },
                        new
                        {
                            Id = 30,
                            CaseId = 2,
                            Description = "The roof hatch was opened earlier that afternoon for routine antenna maintenance. No activity was recorded during the murder.",
                            ImageUrl = "/images/evidence/roof_access.jpg",
                            Name = "Roof Access Log"
                        },
                        new
                        {
                            Id = 31,
                            CaseId = 2,
                            Description = "A receipt timestamped 9:12 PM showing Liza purchased two coffees several blocks away from the station.",
                            ImageUrl = "/images/evidence/coffee_receipt.jpg",
                            Name = "Coffee Shop Receipt"
                        },
                        new
                        {
                            Id = 32,
                            CaseId = 2,
                            Description = "Reception attendance sheets reveal Tina forged employee time records several weeks earlier to help her younger brother keep his job.",
                            ImageUrl = "/images/evidence/attendance_log.jpg",
                            Name = "Attendance Log"
                        },
                        new
                        {
                            Id = 33,
                            CaseId = 2,
                            Description = "A blurry CCTV frame captures a white delivery van leaving the station district after the murder. The license plate is unreadable, and investigators never identify the driver.",
                            ImageUrl = "/images/evidence/white_van.jpg",
                            Name = "White Van CCTV"
                        },
                        new
                        {
                            Id = 8,
                            CaseId = 3,
                            Description = "A common cane-cutting bolo, found half-buried near the chapel path. Nearly every household on the hacienda owns one identical to it.",
                            ImageUrl = "/images/evidence/bolo.jpg",
                            Name = "Bloodied Bolo"
                        },
                        new
                        {
                            Id = 9,
                            CaseId = 3,
                            Description = "A single page torn from the sale agreement, the tenant-eviction clause circled hard enough to tear the paper. Found tucked behind the santo on the chapel altar.",
                            ImageUrl = "/images/evidence/contract_page.jpg",
                            Name = "Torn Land Sale Contract"
                        },
                        new
                        {
                            Id = 10,
                            CaseId = 3,
                            Description = "A handwritten ledger tallying five months of unpaid wages owed to the cane workers, found in a nipa hut at the edge of the fields - the entries stop the day Ernesto died.",
                            ImageUrl = "/images/evidence/wage_ledger.jpg",
                            Name = "Ledger of Unpaid Sacada Wages"
                        },
                        new
                        {
                            Id = 11,
                            CaseId = 3,
                            Description = "A short, cold note in Ernesto's handwriting: 'The allowance stops the day I sign. Don't make this harder than it needs to be.'",
                            ImageUrl = "/images/evidence/note_teresa.jpg",
                            Name = "Threatening Note to Teresa"
                        },
                        new
                        {
                            Id = 12,
                            CaseId = 3,
                            Description = "An estate bank passbook with three withdrawals in Atty. Cruz's handwriting that were never logged in the official trust records.",
                            ImageUrl = "/images/evidence/passbook.jpg",
                            Name = "Bank Passbook with Shortages"
                        },
                        new
                        {
                            Id = 13,
                            CaseId = 3,
                            Description = "An overdue-payment letter from a Manila casino, addressed to Ricardo, threatening 'further action' if the balance isn't settled by month's end.",
                            ImageUrl = "/images/evidence/casino_letter.jpg",
                            Name = "Casino Debt Collector Letter"
                        },
                        new
                        {
                            Id = 14,
                            CaseId = 3,
                            Description = "An old land survey with a section re-measured in Loreta's handwriting, the margin noting 'this was never his to sell alone.'",
                            ImageUrl = "/images/evidence/survey.jpg",
                            Name = "Disputed Boundary Survey"
                        },
                        new
                        {
                            Id = 15,
                            CaseId = 3,
                            Description = "William Tan's business card, a lower price scrawled on the back along with the words 'final take it or we walk.'",
                            ImageUrl = "/images/evidence/business_card.jpg",
                            Name = "Business Card with Scribbled Offer"
                        },
                        new
                        {
                            Id = 16,
                            CaseId = 4,
                            Description = "A standard dive knife, the kind every instructor and boat crew on the property carries. No initials, no distinguishing marks.",
                            ImageUrl = "/images/evidence/dive_knife.jpg",
                            Name = "Diving Knife"
                        },
                        new
                        {
                            Id = 17,
                            CaseId = 4,
                            Description = "An environmental clearance form for the cove expansion, the approval signature traced rather than signed and initialed N.A. in the corner margin.",
                            ImageUrl = "/images/evidence/forged_permit.jpg",
                            Name = "Forged Permit Application"
                        },
                        new
                        {
                            Id = 18,
                            CaseId = 4,
                            Description = "A second, unofficial ledger found taped beneath the office desk drawer, tracking three years of maintenance budget quietly redirected to a personal account.",
                            ImageUrl = "/images/evidence/fund_ledger.jpg",
                            Name = "Diverted Maintenance Fund Ledger"
                        },
                        new
                        {
                            Id = 19,
                            CaseId = 4,
                            Description = "A policy naming Cristina as sole beneficiary, dated two months after the wedding and never disclosed to Ramon's children from his first marriage.",
                            ImageUrl = "/images/evidence/insurance_policy.jpg",
                            Name = "Life Insurance Policy"
                        },
                        new
                        {
                            Id = 20,
                            CaseId = 4,
                            Description = "An envelope of cash found in Mayor Villaruz's car, a sticky note attached reading 'para sa fast-track, huwag na banggitin.'",
                            ImageUrl = "/images/evidence/bribe_envelope.jpg",
                            Name = "Bribery Cash Envelope"
                        },
                        new
                        {
                            Id = 21,
                            CaseId = 4,
                            Description = "A phone photo of the resort's dive compressor with a cut hose taken the same week Boyet was overheard threatening to 'make sure the showcase doesn't go smoothly.'",
                            ImageUrl = "/images/evidence/compressor_photo.jpg",
                            Name = "Sabotaged Compressor Photo"
                        },
                        new
                        {
                            Id = 22,
                            CaseId = 4,
                            Description = "A flyer from the fisherfolk association, hand-annotated in the margin: 'kung kailangan, gagamit tayo ng ibang paraan' (if necessary, we'll use other means).",
                            ImageUrl = "/images/evidence/protest_flyer.jpg",
                            Name = "Protest Flyer"
                        },
                        new
                        {
                            Id = 23,
                            CaseId = 4,
                            Description = "A half-burned copy of the Mangyan community's ancestral domain petition, found in the resort office trash bin someone tried to make it disappear before the investors saw it.",
                            ImageUrl = "/images/evidence/burnt_petition.jpg",
                            Name = "Burnt Petition Copy"
                        });
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.PlayerCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CaseId");

                    b.ToTable("PlayerCases");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Suspect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alibi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGuilty")
                        .HasColumnType("bit");

                    b.Property<string>("Motive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Suspects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alibi = "Claims he was in the control booth the entire evening.",
                            CaseId = 1,
                            Description = "The concert hall's stage manager. Nervous, evasive, avoids eye contact.",
                            ImageUrl = "/images/suspects/marcus.jpg",
                            IsGuilty = false,
                            Motive = "Was recently fired by the violinist for stealing sheet music royalties.",
                            Name = "Marcus Feld"
                        },
                        new
                        {
                            Id = 2,
                            Alibi = "Says she was at a nearby cafe, but no one can confirm it.",
                            CaseId = 1,
                            Description = "A rival violinist who lost the lead position to the victim last season.",
                            ImageUrl = "/images/suspects/elena.jpg",
                            IsGuilty = true,
                            Motive = "Publicly humiliated when passed over for the solo spot.",
                            Name = "Elena Vasquez"
                        },
                        new
                        {
                            Id = 3,
                            Alibi = "Says he was greeting donors in the lobby all evening mostly true, but he was unaccounted for a 15-minute window.",
                            CaseId = 1,
                            Description = "The concert hall's owner and producer. Smooth talker, expensive suit, always working the room.",
                            ImageUrl = "/images/suspects/victor.jpg",
                            IsGuilty = false,
                            Motive = "The violinist had discovered irregularities in the hall's finances and threatened to go public before the show.",
                            Name = "Victor Hale"
                        },
                        new
                        {
                            Id = 4,
                            Alibi = "Claims she was home sick but no one can confirm it, and her phone was off all night.",
                            CaseId = 1,
                            Description = "The violinist's longtime personal assistant. Quiet, meticulous, always one step behind her.",
                            ImageUrl = "/images/suspects/sophia.jpg",
                            IsGuilty = false,
                            Motive = "Learned two days ago that she'd been written out of the violinist's will after years of unpaid overtime.",
                            Name = "Sophia Reyes"
                        },
                        new
                        {
                            Id = 5,
                            Alibi = "Says he was at the bar the whole time bartender remembers seeing him, but not exactly when he left.",
                            CaseId = 1,
                            Description = "The violinist's ex-fiancé. Showed up uninvited backstage an hour before the show.",
                            ImageUrl = "/images/suspects/damian.jpg",
                            IsGuilty = false,
                            Motive = "Still bitter over their public breakup; was overheard arguing with her in the hallway.",
                            Name = "Damian Cole"
                        },
                        new
                        {
                            Id = 18,
                            Alibi = "Claims she left to buy coffee before the broadcast ended. A receipt supports her story.",
                            CaseId = 2,
                            Description = "The station producer. Organized every broadcast and managed the daily schedule.",
                            ImageUrl = "/images/suspects/liza.jpg",
                            IsGuilty = false,
                            Motive = "Miguel planned to replace her after months of declining ratings.",
                            Name = "Liza Mendoza"
                        },
                        new
                        {
                            Id = 19,
                            Alibi = "Says he spent the evening repairing speakers in Studio B.",
                            CaseId = 2,
                            Description = "Senior sound engineer responsible for maintaining Studio B.",
                            ImageUrl = "/images/suspects/noel.jpg",
                            IsGuilty = false,
                            Motive = "Miguel accused him of stealing expensive recording equipment.",
                            Name = "Noel Santos"
                        },
                        new
                        {
                            Id = 20,
                            Alibi = "Claims he was attending a charity dinner throughout the evening.",
                            CaseId = 2,
                            Description = "A local politician frequently criticized on Miguel's radio program.",
                            ImageUrl = "/images/suspects/reyes.jpg",
                            IsGuilty = false,
                            Motive = "Miguel planned to expose corruption involving flood-relief funds.",
                            Name = "Councilor Adrian Reyes"
                        },
                        new
                        {
                            Id = 21,
                            Alibi = "Claims she remained at the front desk until police arrived.",
                            CaseId = 2,
                            Description = "Receptionist responsible for visitor records and station access.",
                            ImageUrl = "/images/suspects/tina.jpg",
                            IsGuilty = false,
                            Motive = "Miguel publicly embarrassed her brother during an investigative segment.",
                            Name = "Tina Flores"
                        },
                        new
                        {
                            Id = 22,
                            Alibi = "Claims he spent the blackout inspecting the generator outside.",
                            CaseId = 2,
                            Description = "Station maintenance technician. Quiet, dependable, and the first to help investigators search the building.",
                            ImageUrl = "/images/suspects/marco.jpg",
                            IsGuilty = true,
                            Motive = "He secretly diverted station maintenance funds to pay for his son's heart surgery and feared Miguel had discovered the missing money.",
                            Name = "Marco Villanueva"
                        },
                        new
                        {
                            Id = 6,
                            Alibi = "Says he was watching the fireworks with cousins the whole time. A few vaguely recall seeing him 'at some point' during the display.",
                            CaseId = 3,
                            Description = "Ernesto's estranged son, back from Manila after nearly a decade of silence arriving just three days before his father's death.",
                            ImageUrl = "/images/suspects/ricardo.jpg",
                            IsGuilty = false,
                            Motive = "Cut off financially years ago and only recently reconciled. With the land sale unsigned, he stood to inherit everything.",
                            Name = "Ricardo Malinao"
                        },
                        new
                        {
                            Id = 7,
                            Alibi = "Claims she left before the fireworks even started. The gate guard's logbook has no exit time recorded for her that night.",
                            CaseId = 3,
                            Description = "Ernesto's longtime companion, kept quietly in a house at the edge of town for over a decade.",
                            ImageUrl = "/images/suspects/teresa.jpg",
                            IsGuilty = false,
                            Motive = "Ernesto was ending their arrangement to remarry once the sale went through cutting off her monthly allowance for good.",
                            Name = "Teresa Bautista"
                        },
                        new
                        {
                            Id = 8,
                            Alibi = "Says he was drafting the final contract in the guest room all night. No one else can confirm he was there the whole time.",
                            CaseId = 3,
                            Description = "The family's lawyer and Ernesto's compadre of thirty years, handling the estate's finances and the pending sale.",
                            ImageUrl = "/images/suspects/cruz.jpg",
                            IsGuilty = false,
                            Motive = "The incoming buyer's audit would have exposed years of quietly siphoned trust funds.",
                            Name = "Atty. Simeon Cruz"
                        },
                        new
                        {
                            Id = 9,
                            Alibi = "Says she was arranging the fireworks display with the caterers. Staff remember her there for 'most of the evening.'",
                            CaseId = 3,
                            Description = "Ernesto's older sister, who ran the hacienda's day-to-day operations for thirty years while he lived abroad.",
                            ImageUrl = "/images/suspects/loreta.jpg",
                            IsGuilty = false,
                            Motive = "Passed over in the will in favor of Ricardo, despite three decades of unpaid work keeping the estate afloat.",
                            Name = "Loreta Malinao"
                        },
                        new
                        {
                            Id = 10,
                            Alibi = "Says he was in the chapel praying through the fireworks, as he does every fiesta. No one thought to check.",
                            CaseId = 3,
                            Description = "The hacienda's katiwala overseer of the cane fields for over forty years. Quiet, devout, tends the small chapel on the property himself.",
                            ImageUrl = "/images/suspects/fidel.jpg",
                            IsGuilty = true,
                            Motive = "The sale would evict the sacada families who'd worked the land for generations families whose wages Ernesto had already quietly stopped paying months ago.",
                            Name = "Mang Fidel Cortez"
                        },
                        new
                        {
                            Id = 11,
                            Alibi = "Says he was on a call with his office in Manila during the fireworks. Phone records confirm a call, but not that he was the one on it.",
                            CaseId = 3,
                            Description = "Representative for the conglomerate buying the land flew in from Manila that morning to finalize the sale.",
                            ImageUrl = "/images/suspects/tan.jpg",
                            IsGuilty = false,
                            Motive = "Ernesto tried to renegotiate the price at the last minute, threatening to walk away from the deal entirely.",
                            Name = "William Tan"
                        },
                        new
                        {
                            Id = 12,
                            Alibi = "Says he was doing late inventory in the resort office alone. No one thought to question it he's always the last one to leave.",
                            CaseId = 4,
                            Description = "Ramon's nephew and the resort's general manager, trusted with the books for the past six years.",
                            ImageUrl = "/images/suspects/nico.jpg",
                            IsGuilty = true,
                            Motive = "An outside audit tied to the expansion loan would have surfaced years of diverted maintenance funds and forged permit paperwork - all under his signature.",
                            Name = "Nico Aguilar"
                        },
                        new
                        {
                            Id = 13,
                            Alibi = "Claims she was greeting investors at the showcase all night. Several guests confirm seeing her but not continuously.",
                            CaseId = 4,
                            Description = "Ramon's second wife, twenty years his junior, married just three years ago.",
                            ImageUrl = "/images/suspects/cristina.jpg",
                            IsGuilty = false,
                            Motive = "Sole beneficiary on a life insurance policy Ramon took out shortly after their wedding one his first family never knew existed.",
                            Name = "Cristina Aguilar"
                        },
                        new
                        {
                            Id = 14,
                            Alibi = "Says his boat never left Sabang that night. The marina logbook backs him up mostly; there's a 40-minute gap in the entries.",
                            CaseId = 4,
                            Description = "Owner of a rival dive resort in Sabang, and Ramon's business rival for over a decade.",
                            ImageUrl = "/images/suspects/boyet.jpg",
                            IsGuilty = false,
                            Motive = "Ramon's expansion would have driven half of Boyet's dive tourists to the new cove, likely closing his resort within a year.",
                            Name = "Boyet Ramos"
                        },
                        new
                        {
                            Id = 15,
                            Alibi = "Says he left the showcase early with a headache. His driver confirms dropping him home, but not what time he arrived.",
                            CaseId = 4,
                            Description = "The town mayor, who fast-tracked the resort's expansion permits over the objections of his own municipal planning office.",
                            ImageUrl = "/images/suspects/villaruz.jpg",
                            IsGuilty = false,
                            Motive = "Ramon was the only person who could prove the permits were approved in exchange for a cut of the investor funding.",
                            Name = "Mayor Teodoro Villaruz"
                        },
                        new
                        {
                            Id = 16,
                            Alibi = "Says he was leading a prayer gathering with his community at the edge of the property when the fireworks started. Several members confirm it.",
                            CaseId = 4,
                            Description = "An elder of the local Mangyan community, who has spent months formally petitioning to have the cove recognized as ancestral domain.",
                            ImageUrl = "/images/suspects/bandying.jpg",
                            IsGuilty = false,
                            Motive = "The expansion would pave over a burial ground his community has protected for generations and Ramon had ignored every petition.",
                            Name = "Datu Bandying"
                        },
                        new
                        {
                            Id = 17,
                            Alibi = "Says he was leading the protest chant outside the gate when the fireworks went off dozens of witnesses can place him there.",
                            CaseId = 4,
                            Description = "Head of the local fisherfolk association, and the loudest voice at every protest outside the resort gate for the past two months.",
                            ImageUrl = "/images/suspects/pandoy.jpg",
                            IsGuilty = false,
                            Motive = "The cove is the fishing ground his association depends on. Losing it meant losing livelihoods for over thirty families.",
                            Name = "Fernando \"Ka Pandoy\" Reyes"
                        });
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.SuspectElimination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EliminatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SuspectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CaseId");

                    b.HasIndex("SuspectId");

                    b.ToTable("SuspectEliminations");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Witness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Witnesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseId = 1,
                            ImageUrl = "/images/witnesses/janitor.jpg",
                            Name = "Backstage Janitor",
                            Statement = "I saw someone in a dark coat near the dressing rooms around 7:40 PM, but I didn't get a good look at their face."
                        },
                        new
                        {
                            Id = 2,
                            CaseId = 1,
                            ImageUrl = "/images/witnesses/clerk.jpg",
                            Name = "Ticket Booth Clerk",
                            Statement = "A woman matching Elena's description left in a hurry just before intermission. She seemed upset."
                        },
                        new
                        {
                            Id = 3,
                            CaseId = 1,
                            ImageUrl = "/images/witnesses/sound_tech.jpg",
                            Name = "Sound Technician",
                            Statement = "I overheard Victor Hale on the phone saying something like 'we need to make the numbers disappear before anyone audits this.' Didn't think much of it at the time."
                        },
                        new
                        {
                            Id = 4,
                            CaseId = 1,
                            ImageUrl = "/images/witnesses/valet.jpg",
                            Name = "Valet",
                            Statement = "Damian Cole's car peeled out of the lot around 9 PM, tires screeching. Looked like he was in a real hurry to leave."
                        },
                        new
                        {
                            Id = 14,
                            CaseId = 2,
                            ImageUrl = "/images/witnesses/security_guard_radio.jpg",
                            Name = "Security Guard",
                            Statement = "I heard something heavy hit the floor around 9:24 PM. I assumed a microphone stand had fallen."
                        },
                        new
                        {
                            Id = 15,
                            CaseId = 2,
                            ImageUrl = "/images/witnesses/coffee_vendor.jpg",
                            Name = "Coffee Vendor",
                            Statement = "The producer bought coffee just after nine. She looked rushed but never returned before the police arrived."
                        },
                        new
                        {
                            Id = 16,
                            CaseId = 2,
                            ImageUrl = "/images/witnesses/janitor_radio.jpg",
                            Name = "Janitor",
                            Statement = "I saw someone carrying a flashlight outside near the generator shed. It was raining too hard to recognize who it was."
                        },
                        new
                        {
                            Id = 17,
                            CaseId = 2,
                            ImageUrl = "/images/witnesses/listener.jpg",
                            Name = "Regular Listener",
                            Statement = "The broadcast suddenly stopped. Everyone online thought the neighborhood had lost power."
                        },
                        new
                        {
                            Id = 18,
                            CaseId = 2,
                            ImageUrl = "/images/witnesses/delivery_rider.jpg",
                            Name = "Delivery Rider",
                            Statement = "A white van left the station shortly after the police arrived. I couldn't read the plate because of the rain."
                        },
                        new
                        {
                            Id = 5,
                            CaseId = 3,
                            ImageUrl = "/images/witnesses/nena.jpg",
                            Name = "Nena, the Kasambahay",
                            Statement = "I saw someone pass by the study window right when the fireworks started, pero patalikod siya (back was turned), couldn't tell you who."
                        },
                        new
                        {
                            Id = 6,
                            CaseId = 3,
                            ImageUrl = "/images/witnesses/tricycle_driver.jpg",
                            Name = "Tricycle Driver",
                            Statement = "I drove Ricardo to town earlier that day. He was on the phone the whole ride, arguing with someone about a debt- sounded serious."
                        },
                        new
                        {
                            Id = 7,
                            CaseId = 3,
                            ImageUrl = "/images/witnesses/councilor.jpg",
                            Name = "Town Councilor",
                            Statement = "I saw Atty. Cruz slip out of the fiesta early, clutching a folder like his life depended on it. Didn't even say goodbye to anyone."
                        },
                        new
                        {
                            Id = 8,
                            CaseId = 3,
                            ImageUrl = "/images/witnesses/farmhand.jpg",
                            Name = "Sacada Farmhand",
                            Statement = "Nakita ko si Mang Fidel walking from the chapel toward the main house right before the fireworks ended, may dalang something wrapped in cloth. Sabi niya nagdadasal lang daw siya kanina, pero hindi galing sa kapilya papunta kundi papunta sa bahay."
                        },
                        new
                        {
                            Id = 9,
                            CaseId = 3,
                            ImageUrl = "/images/witnesses/niece.jpg",
                            Name = "Ernesto's Niece",
                            Statement = "I saw Tita Teresa and Tito Ernesto arguing near the garden earlier that evening, before the fireworks even started. She looked like she'd been crying."
                        },
                        new
                        {
                            Id = 10,
                            CaseId = 4,
                            ImageUrl = "/images/witnesses/bangkero.jpg",
                            Name = "Bangkero (Boat Captain)",
                            Statement = "Merong nakita akong tao malapit sa dive shop that night, pero madilim hindi ko masabi kung sino."
                        },
                        new
                        {
                            Id = 11,
                            CaseId = 4,
                            ImageUrl = "/images/witnesses/front_desk.jpg",
                            Name = "Resort Front Desk Staff",
                            Statement = "I overheard Cristina on the phone that night saying, 'after this, wala nang makakapigil sa 'kin.' Didn't think much of it at the time."
                        },
                        new
                        {
                            Id = 12,
                            CaseId = 4,
                            ImageUrl = "/images/witnesses/sabang_local.jpg",
                            Name = "Sabang Local",
                            Statement = "I saw Boyet's boat idling near the resort's private dock that night, lights off. Left again after maybe ten minutes."
                        },
                        new
                        {
                            Id = 13,
                            CaseId = 4,
                            ImageUrl = "/images/witnesses/security_guard.jpg",
                            Name = "Resort Security Guard",
                            Statement = "Si Nico lang ang nakita kong pumasok sa office nang mag-isa, late na late na. Sabi niya nagta-take lang daw siya ng inventory, pero nakita ko siyang may dalang shredder bag paglabas."
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Accusation", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Suspect", "AccusedSuspect")
                        .WithMany()
                        .HasForeignKey("AccusedSuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("Accusations")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccusedSuspect");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.CaseConnection", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("CaseConnections")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.ClueConnection", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("ClueConnections")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.ConnectionAttempt", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Evidence", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("EvidenceItems")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.PlayerCase", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("PlayerCases")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Suspect", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("Suspects")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.SuspectElimination", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("SuspectEliminations")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Suspect", "Suspect")
                        .WithMany()
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Case");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Witness", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("Witnesses")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Case", b =>
                {
                    b.Navigation("Accusations");

                    b.Navigation("CaseConnections");

                    b.Navigation("ClueConnections");

                    b.Navigation("EvidenceItems");

                    b.Navigation("PlayerCases");

                    b.Navigation("SuspectEliminations");

                    b.Navigation("Suspects");

                    b.Navigation("Witnesses");
                });
#pragma warning restore 612, 618
        }
    }
}
