// <auto-generated />
using System;
using DigitalDetectiveAgency.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalDetectiveAgency.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260805024437_AddVictimNameToCase")]
    partial class AddVictimNameToCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Accusation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccusedSuspectId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccusedSuspectId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CaseId");

                    b.ToTable("Accusations");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("HasCompletedTutorial")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VictimName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Description = "Jeepney operator Ramon \"Mon\" Padilla is found dead behind his terminal office in Malate, struck once with a tire iron. No forced entry, no witnesses to the act itself. His ledger of quiet arrangements colorum payments, a personal loan, and a land sale he was hiding from his partners gives half the neighborhood a reason to want him gone. Only one of them was actually there.",
                            Difficulty = 2,
                            IsPublished = true,
                            Title = "The Last Jeepney to Malate",
                            VictimName = "Ramon \"Mon\" Padilla"
                        });
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.CaseConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int>("FromId")
                        .HasColumnType("int");

                    b.Property<string>("FromType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToId")
                        .HasColumnType("int");

                    b.Property<string>("ToType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("CaseConnections");

                    b.HasData(
                        new
                        {
                            Id = 17,
                            CaseId = 5,
                            FromId = 34,
                            FromType = "Evidence",
                            Note = "The floor wax on the tire iron isn't from the terminal. It's from the barangay hall.",
                            ToId = 27,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 18,
                            CaseId = 5,
                            FromId = 35,
                            FromType = "Evidence",
                            Note = "\"RV.\" The initials on the surviving carbon copy aren't a coincidence.",
                            ToId = 27,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 19,
                            CaseId = 5,
                            FromId = 20,
                            FromType = "Witness",
                            Note = "The barong-shirt figure on Nena's CCTV walks Rey's usual patrol route.",
                            ToId = 27,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 20,
                            CaseId = 5,
                            FromId = 40,
                            FromType = "Evidence",
                            Note = "No sign-in time. Whatever Rey was doing during that gap, it wasn't logged and it wasn't at the hall.",
                            ToId = 27,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 21,
                            CaseId = 5,
                            FromId = 41,
                            FromType = "Evidence",
                            Note = "Same wax residue as the weapon. Same place, same night.",
                            ToId = 27,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 22,
                            CaseId = 5,
                            FromId = 19,
                            FromType = "Witness",
                            Note = "Baby's account accounts for nearly all of Elena's time. The alley gap was real, but far too short.",
                            ToId = 23,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 23,
                            CaseId = 5,
                            FromId = 22,
                            FromType = "Witness",
                            Note = "The dinner alibi holds. Ferdie was nowhere near Malate that night.",
                            ToId = 25,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 24,
                            CaseId = 5,
                            FromId = 21,
                            FromType = "Witness",
                            Note = "Dindo did go inside but only to leave a payment. He found nothing but an empty office and ran.",
                            ToId = 24,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 25,
                            CaseId = 5,
                            FromId = 42,
                            FromType = "Evidence",
                            Note = "Grace's shift log is locked in, third-party verified. She was never near Malate that night.",
                            ToId = 26,
                            ToType = "Suspect"
                        });
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.ClueConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromId")
                        .HasColumnType("int");

                    b.Property<string>("FromType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToId")
                        .HasColumnType("int");

                    b.Property<string>("ToType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CaseId");

                    b.ToTable("ClueConnections");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.ConnectionAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromId")
                        .HasColumnType("int");

                    b.Property<string>("FromType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToId")
                        .HasColumnType("int");

                    b.Property<string>("ToType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WasCorrect")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CaseId");

                    b.ToTable("ConnectionAttempts");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("EvidenceItems");

                    b.HasData(
                        new
                        {
                            Id = 34,
                            CaseId = 5,
                            Description = "The murder weapon, wiped clean of prints. A faint smear on the handle doesn't match anything at the terminal it tests as floor wax, the kind used at the barangay hall.",
                            ImageUrl = "/images/case_1/evidence/tire_iron.jpg",
                            Name = "Tire Iron"
                        },
                        new
                        {
                            Id = 35,
                            CaseId = 5,
                            Description = "Most of Mon's ledger was burned, but a carbon-copy undersheet survived. One legible line reads '...facilitation fee RV...' before the char damage cuts it off.",
                            ImageUrl = "/images/case_1/evidence/burnt_ledger.jpg",
                            Name = "Burnt Ledger Page"
                        },
                        new
                        {
                            Id = 36,
                            CaseId = 5,
                            Description = "A grainy frame from the store across the street, timestamped 11:20 PM. A figure in a barong-adjacent shirt common among barangay officials passes near the terminal. The face isn't visible.",
                            ImageUrl = "/images/case_1/evidence/cctv_still.jpg",
                            Name = "Sari-Sari Store CCTV Still"
                        },
                        new
                        {
                            Id = 37,
                            CaseId = 5,
                            Description = "Found in Mon's desk drawer. Dindo's name and a partial amount are written on the front proof he was there, but nothing more.",
                            ImageUrl = "/images/case_1/evidence/payment_envelope.jpg",
                            Name = "Dindo's Payment Envelope"
                        },
                        new
                        {
                            Id = 38,
                            CaseId = 5,
                            Description = "A neighbor's unrelated Facebook photo, taken in the alley behind the carinderia at 11:25 PM. Elena is visible in the background, taking out trash.",
                            ImageUrl = "/images/case_1/evidence/alley_photo.jpg",
                            Name = "Alley Timestamp Photo"
                        },
                        new
                        {
                            Id = 39,
                            CaseId = 5,
                            Description = "A testy back-and-forth on Mon's phone about the renegotiated lot price. The exchange ends at 9:50 PM too early to place Ferdie at the scene.",
                            ImageUrl = "/images/case_1/evidence/text_exchange.jpg",
                            Name = "Text Exchange with Ferdie"
                        },
                        new
                        {
                            Id = 40,
                            CaseId = 5,
                            Description = "Kap. Rey signed out at 10:50 PM for 'patrol.' There's no sign-back-in time until well after midnight an unaccounted gap that covers the time of the murder.",
                            ImageUrl = "/images/case_1/evidence/barangay_logbook.jpg",
                            Name = "Barangay Hall Logbook"
                        },
                        new
                        {
                            Id = 41,
                            CaseId = 5,
                            Description = "A faint rubber-sandal print in the dust near the body. Common brand, not unique on its own but it carries the same floor wax residue found on the tire iron.",
                            ImageUrl = "/images/case_1/evidence/shoeprint.jpg",
                            Name = "Partial Shoeprint"
                        },
                        new
                        {
                            Id = 42,
                            CaseId = 5,
                            Description = "A time-stamped nursing shift record placing Grace at a Quezon City hospital from before 9 PM until well past midnight. Locked-in, third-party verified.",
                            ImageUrl = "/images/case_1/evidence/hospital_log.jpg",
                            Name = "Hospital Shift Log"
                        });
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.PlayerCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CaseId");

                    b.ToTable("PlayerCases");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Suspect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alibi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGuilty")
                        .HasColumnType("bit");

                    b.Property<string>("Motive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Suspects");

                    b.HasData(
                        new
                        {
                            Id = 23,
                            Alibi = "Says she was closing up the carinderia until past midnight, with her helper Baby there the whole time preparing for the next day. Mentions a gas delivery Baby signed for around 11 PM.",
                            CaseId = 5,
                            Description = "Mon's estranged wife, 48. Runs a small carinderia two blocks from the terminal.",
                            ImageUrl = "/images/case_1/suspects/elena_padilla.jpg",
                            IsGuilty = false,
                            Motive = "Mon was finalizing the terminal lot sale without telling her she'd get nothing from it despite twenty years of marriage; the annulment was never finalized.",
                            Name = "Elena Padilla"
                        },
                        new
                        {
                            Id = 24,
                            Alibi = "Says he dropped his jeep off at the terminal around 11:15 PM and left immediately the terminal was already dark, so he never went inside, just left his keys in the drop box.",
                            CaseId = 5,
                            Description = "One of Mon's four drivers, 34. Deep in personal debt to Mon, on top of his fleet obligations.",
                            ImageUrl = "/images/case_1/suspects/dindo_reyes.jpg",
                            IsGuilty = false,
                            Motive = "Owed Mon ₱45,000 personally; Mon had started deducting it aggressively from his daily boundary, leaving little for his family.",
                            Name = "Dindo Reyes"
                        },
                        new
                        {
                            Id = 25,
                            Alibi = "Says he was at a client dinner in Makati until 10:30 PM, then went straight home to Parañaque naming the restaurant and his dinner companion without hesitation.",
                            CaseId = 5,
                            Description = "Local representative for the developer negotiating to buy the terminal lot, 45.",
                            ImageUrl = "/images/case_1/suspects/ferdie_bautista.jpg",
                            IsGuilty = false,
                            Motive = "The sale was stalling after Mon demanded a higher price at the last minute. A collapsed deal would cost Ferdie his commission and standing with the developer.",
                            Name = "Architect Ferdie Bautista"
                        },
                        new
                        {
                            Id = 26,
                            Alibi = "Says she was on shift at a hospital in Quezon City until past midnight.",
                            CaseId = 5,
                            Description = "Mon's estranged daughter from a prior relationship, 26. Works as a nurse, rarely spoke to her father.",
                            ImageUrl = "/images/case_1/suspects/grace_sison.jpg",
                            IsGuilty = false,
                            Motive = "Recently reconnected with Mon, who reportedly intended to leave her a share of the terminal lot cutting into what Elena or the drivers might expect.",
                            Name = "Grace Padilla-Sison"
                        },
                        new
                        {
                            Id = 27,
                            Alibi = "Says he was doing late paperwork alone at the barangay hall no one to corroborate it, but insists the logbook proves he was there.",
                            CaseId = 5,
                            Description = "Barangay captain, 58. Has known Mon for thirty years and quietly brokered the terminal lot deal for a personal cut.",
                            ImageUrl = "/images/case_1/suspects/rey_villamor.jpg",
                            IsGuilty = true,
                            Motive = "Stood to lose a facilitation fee he'd already spent if Mon backed out of the sale after deciding to cut Grace in and shrink Rey's share.",
                            Name = "Kap. Rey Villamor"
                        });
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.SuspectElimination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EliminatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SuspectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CaseId");

                    b.HasIndex("SuspectId");

                    b.ToTable("SuspectEliminations");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Witness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Witnesses");

                    b.HasData(
                        new
                        {
                            Id = 19,
                            CaseId = 5,
                            ImageUrl = "/images/case_1/witnesses/baby.jpg",
                            Name = "Baby (Carinderia Helper)",
                            Statement = "Naglagay pa kami ng sinigang mix para bukas, tapos may dumating na gas delivery mga alas-onse. Si Aling Elena, saglit lang siyang lumabas maglalabas ng basura sa eskinita. Hindi naman tumagal, ten minutes lang siguro."
                        },
                        new
                        {
                            Id = 20,
                            CaseId = 5,
                            ImageUrl = "/images/case_1/witnesses/aling_nena.jpg",
                            Name = "Aling Nena (Sari-Sari Store Owner)",
                            Statement = "May CCTV kami dun sa labas, nakuhanan namin ng lumabas na parang naka-barong sa may terminal. Hindi ko masyadong nakita ang mukha. Alam mo, madalas naman dumaan si Kapitan dun kapag 'patrol' daw niya."
                        },
                        new
                        {
                            Id = 21,
                            CaseId = 5,
                            ImageUrl = "/images/case_1/witnesses/jun.jpg",
                            Name = "Jun (Fellow Driver)",
                            Statement = "Bumalik si Dindo sa terminal after niya i-drop yung huling byahe niya. May ibinigay siyang envelope, sabi niya kay Mon daw. Mabilis lang siya, umalis din agad."
                        },
                        new
                        {
                            Id = 22,
                            CaseId = 5,
                            ImageUrl = "/images/case_1/witnesses/dinner_companion.jpg",
                            Name = "Ferdie's Dinner Companion",
                            Statement = "We were at the restaurant together until around 10:30 he left straight after, said he was heading home to Parañaque. I remember because he complained about the traffic before he even got in his car."
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Accusation", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Suspect", "AccusedSuspect")
                        .WithMany()
                        .HasForeignKey("AccusedSuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("Accusations")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccusedSuspect");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.CaseConnection", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("CaseConnections")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.ClueConnection", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("ClueConnections")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.ConnectionAttempt", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Evidence", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("EvidenceItems")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.PlayerCase", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("PlayerCases")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Suspect", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("Suspects")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.SuspectElimination", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("SuspectEliminations")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Suspect", "Suspect")
                        .WithMany()
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Case");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Witness", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("Witnesses")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Case", b =>
                {
                    b.Navigation("Accusations");

                    b.Navigation("CaseConnections");

                    b.Navigation("ClueConnections");

                    b.Navigation("EvidenceItems");

                    b.Navigation("PlayerCases");

                    b.Navigation("SuspectEliminations");

                    b.Navigation("Suspects");

                    b.Navigation("Witnesses");
                });
#pragma warning restore 612, 618
        }
    }
}
