// <auto-generated />
using System;
using DigitalDetectiveAgency.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DigitalDetectiveAgency.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260724065603_UpdateCase1SeedData")]
    partial class UpdateCase1SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Accusation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccusedSuspectId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AccusedSuspectId");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CaseId");

                    b.ToTable("Accusations");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetectiveName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A world-renowned violinist disappears moments before a sold-out concert. No signs of forced entry. No witnesses. Just an empty dressing room and a single dropped rose.",
                            Difficulty = 0,
                            IsPublished = true,
                            Title = "The Vanishing Violinist"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A wealthy family's annual reunion ends in tragedy when the patriarch is found dead in the locked study. Everyone had a motive. No one has an alibi.",
                            Difficulty = 1,
                            IsPublished = true,
                            Title = "Silence at Blackwood Manor"
                        });
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.CaseConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int>("FromId")
                        .HasColumnType("int");

                    b.Property<string>("FromType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToId")
                        .HasColumnType("int");

                    b.Property<string>("ToType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("CaseConnections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseId = 1,
                            FromId = 2,
                            FromType = "Evidence",
                            ToId = 2,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 2,
                            CaseId = 1,
                            FromId = 2,
                            FromType = "Witness",
                            ToId = 2,
                            ToType = "Suspect"
                        },
                        new
                        {
                            Id = 3,
                            CaseId = 1,
                            FromId = 7,
                            FromType = "Evidence",
                            ToId = 2,
                            ToType = "Suspect"
                        });
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.ClueConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromId")
                        .HasColumnType("int");

                    b.Property<string>("FromType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToId")
                        .HasColumnType("int");

                    b.Property<string>("ToType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CaseId");

                    b.ToTable("ClueConnections");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Evidence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("EvidenceItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseId = 1,
                            Description = "A single red rose found on the dressing room floor. The stem is freshly cut, not wilted — someone left it here recently.",
                            ImageUrl = "/images/evidence/rose.jpg",
                            Name = "Dropped Rose"
                        },
                        new
                        {
                            Id = 2,
                            CaseId = 1,
                            Description = "A concert program torn roughly in half. The violinist's name has been circled in red ink, and a small phone number is scrawled in the margin.",
                            ImageUrl = "/images/evidence/torn_program.jpg",
                            Name = "Torn Concert Program"
                        },
                        new
                        {
                            Id = 3,
                            CaseId = 2,
                            Description = "An antique pocket watch, stopped at 9:47 PM. The glass is cracked, and the inside cover is engraved with initials that don't match anyone in the household.",
                            ImageUrl = "/images/evidence/pocket_watch.jpg",
                            Name = "Broken Pocket Watch"
                        },
                        new
                        {
                            Id = 4,
                            CaseId = 1,
                            Description = "A photocopied ledger page with several transactions circled and the word 'AUDIT' underlined twice. Found stuffed in a lobby trash can.",
                            ImageUrl = "/images/evidence/ledger.jpg",
                            Name = "Insurance Ledger Page"
                        },
                        new
                        {
                            Id = 5,
                            CaseId = 1,
                            Description = "A crumpled note reading: 'We need to talk. I'm not done fighting for us.' No signature, but the handwriting is bold and impatient.",
                            ImageUrl = "/images/evidence/note.jpg",
                            Name = "Handwritten Note"
                        },
                        new
                        {
                            Id = 6,
                            CaseId = 1,
                            Description = "A printed transcript of a voicemail: 'You can't just cut me out after everything I've done for you. We'll see about that.' Timestamp: three days before the disappearance.",
                            ImageUrl = "/images/evidence/voicemail.jpg",
                            Name = "Voicemail Transcript"
                        },
                        new
                        {
                            Id = 7,
                            CaseId = 1,
                            Description = "A printout of badge-scan entries. One badge — registered to Elena Vasquez — scanned into the dressing room corridor at 7:38 PM, twenty minutes before the violinist was last seen.",
                            ImageUrl = "/images/evidence/security_log.jpg",
                            Name = "Backstage Security Log"
                        });
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.PlayerCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpened")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OpenedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CaseId");

                    b.ToTable("PlayerCases");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Suspect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alibi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsGuilty")
                        .HasColumnType("bit");

                    b.Property<string>("Motive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Suspects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alibi = "Claims he was in the control booth the entire evening.",
                            CaseId = 1,
                            Description = "The concert hall's stage manager. Nervous, evasive, avoids eye contact.",
                            ImageUrl = "/images/suspects/marcus.jpg",
                            IsGuilty = false,
                            Motive = "Was recently fired by the violinist for stealing sheet music royalties.",
                            Name = "Marcus Feld"
                        },
                        new
                        {
                            Id = 2,
                            Alibi = "Says she was at a nearby cafe, but no one can confirm it.",
                            CaseId = 1,
                            Description = "A rival violinist who lost the lead position to the victim last season.",
                            ImageUrl = "/images/suspects/elena.jpg",
                            IsGuilty = true,
                            Motive = "Publicly humiliated when passed over for the solo spot.",
                            Name = "Elena Vasquez"
                        },
                        new
                        {
                            Id = 3,
                            Alibi = "Says he was greeting donors in the lobby all evening — mostly true, but he was unaccounted for a 15-minute window.",
                            CaseId = 1,
                            Description = "The concert hall's owner and producer. Smooth talker, expensive suit, always working the room.",
                            ImageUrl = "/images/suspects/victor.jpg",
                            IsGuilty = false,
                            Motive = "The violinist had discovered irregularities in the hall's finances and threatened to go public before the show.",
                            Name = "Victor Hale"
                        },
                        new
                        {
                            Id = 4,
                            Alibi = "Claims she was home sick — but no one can confirm it, and her phone was off all night.",
                            CaseId = 1,
                            Description = "The violinist's longtime personal assistant. Quiet, meticulous, always one step behind her.",
                            ImageUrl = "/images/suspects/sophia.jpg",
                            IsGuilty = false,
                            Motive = "Learned two days ago that she'd been written out of the violinist's will after years of unpaid overtime.",
                            Name = "Sophia Reyes"
                        },
                        new
                        {
                            Id = 5,
                            Alibi = "Says he was at the bar the whole time — bartender remembers seeing him, but not exactly when he left.",
                            CaseId = 1,
                            Description = "The violinist's ex-fiancé. Showed up uninvited backstage an hour before the show.",
                            ImageUrl = "/images/suspects/damian.jpg",
                            IsGuilty = false,
                            Motive = "Still bitter over their public breakup; was overheard arguing with her in the hallway.",
                            Name = "Damian Cole"
                        });
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.SuspectElimination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EliminatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SuspectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CaseId");

                    b.HasIndex("SuspectId");

                    b.ToTable("SuspectEliminations");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Witness", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Witnesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaseId = 1,
                            ImageUrl = "/images/witnesses/janitor.jpg",
                            Name = "Backstage Janitor",
                            Statement = "I saw someone in a dark coat near the dressing rooms around 7:40 PM, but I didn't get a good look at their face."
                        },
                        new
                        {
                            Id = 2,
                            CaseId = 1,
                            ImageUrl = "/images/witnesses/clerk.jpg",
                            Name = "Ticket Booth Clerk",
                            Statement = "A woman matching Elena's description left in a hurry just before intermission. She seemed upset."
                        },
                        new
                        {
                            Id = 3,
                            CaseId = 1,
                            ImageUrl = "/images/witnesses/sound_tech.jpg",
                            Name = "Sound Technician",
                            Statement = "I overheard Victor Hale on the phone saying something like 'we need to make the numbers disappear before anyone audits this.' Didn't think much of it at the time."
                        },
                        new
                        {
                            Id = 4,
                            CaseId = 1,
                            ImageUrl = "/images/witnesses/valet.jpg",
                            Name = "Valet",
                            Statement = "Damian Cole's car peeled out of the lot around 9 PM, tires screeching. Looked like he was in a real hurry to leave."
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Accusation", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Suspect", "AccusedSuspect")
                        .WithMany()
                        .HasForeignKey("AccusedSuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("Accusations")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AccusedSuspect");

                    b.Navigation("ApplicationUser");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.CaseConnection", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("CaseConnections")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.ClueConnection", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("ClueConnections")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Evidence", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("EvidenceItems")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.PlayerCase", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("PlayerCases")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Suspect", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("Suspects")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.SuspectElimination", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("SuspectEliminations")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Suspect", "Suspect")
                        .WithMany()
                        .HasForeignKey("SuspectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Case");

                    b.Navigation("Suspect");
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Witness", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.Case", "Case")
                        .WithMany("Witnesses")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DigitalDetectiveAgency.Models.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DigitalDetectiveAgency.Models.Entities.Case", b =>
                {
                    b.Navigation("Accusations");

                    b.Navigation("CaseConnections");

                    b.Navigation("ClueConnections");

                    b.Navigation("EvidenceItems");

                    b.Navigation("PlayerCases");

                    b.Navigation("SuspectEliminations");

                    b.Navigation("Suspects");

                    b.Navigation("Witnesses");
                });
#pragma warning restore 612, 618
        }
    }
}
